In [3]:
import numpy as np

In [5]:
lista = [15,10,15,15,15,15,10,12,13,14,8,15]

In [7]:
array = np.array(lista)

In [9]:
array

array([15, 10, 15, 15, 15, 15, 10, 12, 13, 14,  8, 15])

In [27]:
lista2 = [[10,15,14],[1,2,3],[5,6,9]]

In [29]:
array2

array([10, 15, 14,  1,  2,  3,  4,  5,  6,  9])

In [31]:
array2 = np.array(lista2)

In [33]:
array2

array([[10, 15, 14],
       [ 1,  2,  3],
       [ 5,  6,  9]])

In [35]:
lista3 = [[10,12],[15,16]]

In [45]:
array3 = np.array(lista3)

In [47]:
array3

array([[10, 12],
       [15, 16]])