In [1]:
import numpy as np

In [29]:
np.random.rand(5)

array([0.50871547, 0.97053994, 0.17660474, 0.59352378, 0.10828635])

In [31]:
np.random.rand(2,3)

array([[0.04714214, 0.41403413, 0.09686224],
       [0.48544711, 0.34879851, 0.23504239]])

In [35]:
np.random.randn(4)

array([-0.1758716 ,  1.99210938, -0.32633052, -0.07736229])

In [37]:
np.random.randn(4,5)

array([[ 0.73168428, -0.322658  , -1.79935979,  0.84701806,  0.43893001],
       [ 0.06585054,  1.46027042, -0.98156545, -0.19563808,  0.42524618],
       [-1.32582773,  1.29423582, -0.07003178,  0.01435232, -0.39388837],
       [ 0.69881439,  0.60179405, -0.80032409, -0.27695923, -1.21504866]])