In [1]:
import numpy as np

In [35]:
array = np.arange(0,10)

In [37]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
condicion = array>6

In [41]:
condicion

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [47]:
array[condicion]

array([7, 8, 9])