In [5]:
import numpy as np

In [7]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
array[0]

array([1, 2, 3])

In [13]:
array[1]

array([4, 5, 6])

In [15]:
array[2]

array([7, 8, 9])

In [17]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
array[0,0]

1

In [21]:
array[:,0]

array([1, 4, 7])